# Where should we write the GIF?
Output chat-demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 32
Set Width 1200
Set Height 800

# Type a command in the terminal.
Type "./chatbot"

# Pause for dramatic effect...
Sleep 1s

# Run the command by pressing enter.
Enter

Sleep 1s

# Run the command by pressing enter.
Type "Whats the capitol of Maryland?"
Sleep 1s
Enter
Sleep 3s
Type "Explain Golang pointers in 20 words or less"
Sleep 1s
Enter
Sleep 4s
Ctrl+C
